version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      TZ: "Europe/Amsterdam"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
    volumes:
      - pihole-data:/etc/pihole
      - dnsmasq-data:/etc/dnsmasq.d
    network_mode: "host"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN # For DHCP.

volumes:
  pihole-data:
    driver: local
  dnsmasq-data:
    driver: local
