# https://github.com/recurser/string-is

apiVersion: apps/v1
kind: Deployment
metadata:
  name: string-is
  namespace: string-is
  labels:
    app: string-is
spec:
  selector:
    matchLabels:
      app: string-is
  replicas: 1
  template:
    metadata:
      labels:
        app: string-is
    spec:
      containers:
      - name: string-is
        image: daveperrett/string-is:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: string-is
  namespace: string-is
spec:
  selector:
    app: string-is
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: string-is
  namespace: string-is
spec:
  secretName: string-is
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - "string-is.hl.terna.wtf"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: string-is
  namespace: string-is
spec:
  rules:
  - host: "string-is.hl.terna.wtf"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: string-is
            port:
              number: 80
  tls:
  - hosts:
      - string-is.hl.terna.wtf
    secretName: string-is
